# .goreleaser.yml
# Build customization
before:
  hooks:
  - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  binary: bee
sign:
  artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
    - '^doc:'
    - '^test:'
    - Merge pull request
    - Merge branch
